driver:
  name: docker
  use_sudo: false

provisioner:
  name: ansible_push
  playbook: priv/ansible/playbook.yml
  idempotency_test: true
  # Add more v's for more verbose
  verbose: ""

platforms:
  - name: ubuntu-16-docker
    driver_config:
      use_cache: true
      image: ubuntu:16.04

suites:
  - name: single
    driver:
      hostname: single
      forward:
        - 1080:80
        - 10443:443
        - 11443:1443
        - 12443:2443
        - 50051:50051
        - 50052:50052
        - 44451:44451
        - 44452:44452
    provisioner:
      mygroup:
        - grpcserver
