---
- name: Install private TLS key
  template: src=server.key dest=/etc/nginx/server.key
  notify: reload nginx

- name: Install self-signed cert
  template: src=server.crt dest=/etc/nginx/server.crt
  notify: reload nginx
